services:
  database:
    image: mysql:8
    container_name: backend-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      database: 
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=3306

volumes:
  db-data:
