export enum GameType {
  PODIUM = 'PODIUM',
  MONSTER = 'MONSTER',
  EXPERIENCE = 'EXPERIENCE',
}

export enum TypeDisposable {
  PLASTIC_PACKAGING = 'PLASTIC PACKAGING',
  CARDBOARD_PACKAGING = 'CARDBOARD PACKAGING',
  PAPER = 'PAPER',
  GLASS_PACKAGING = 'GLASS PACKAGING',
  METAL_PACKAGING = 'METAL PACKAGING',
  USED = 'USED',
  DAMAGED = 'DAMAGED',
  DISHES = 'DISHES',
  ORGANIC = 'ORGANIC',
  NOT_PACKAGING = 'NOT PACKAGING',
  MEDICINE = 'MEDICINE',
  TOXIC = 'TOXIC',
  DEVICE = 'DEVICE',
  TEXTILE = 'TEXTILE',
  BULKY_WASTE = 'BULKY WASTE',
}

export enum UserType {
  NORMAL = 0,
  ADMIN = 1,
  RESTRICTED = 2,
}
