name: Node.js CI-CD

on:
  push:
    branches: ['*']  # Trigger on all branches

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env-ready: ${{ steps.setup-env.outputs.env-ready }}
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Copy default.env to .env
      - name: Copy default.env to .env
        run: cp default.env .env

      # Install dependencies
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      # Linting check
      - name: Run ESLint
        run: npm run lint

      # Prettier check
      - name: Check formatting with Prettier
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      # Run tests
      - name: Run Jest tests
        run: npm test
