name: Node.js CI

on:
  push:
    branches: ['*'] # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      # Copying the environment variables
      - name: Copy default.env to .env
        run: cp default.env .env

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Linting check
      - name: Run ESLint
        run: npm run lint

      # Prettier check
      - name: Check formatting with Prettier
        run: npm run format:check

      # Run tests
      - name: Run Jest tests
        run: npm test
